steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/nathan-new-sre/sre-training-repo/my-flask-app:${_GIT_TAG}'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/nathan-new-sre/sre-training-repo/my-flask-app:${_GIT_TAG}'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Get GKE Credentials
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'my-flask-cluster'
    - '--zone=us-central1-c'
    - '--project=nathan-new-sre'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy to GKE
  args:
    - 'set'
    - 'image'
    - 'deployment/my-flask-app-deployment'
    - 'my-flask-app-container=us-central1-docker.pkg.dev/nathan-new-sre/sre-training-repo/my-flask-app:${_GIT_TAG}'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'

substitutions:
  _GIT_TAG: 'latest'



