# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app-container
        image: us-central1-docker.pkg.dev/sre-engineering/sre-training-repo/my-flask-app:v1.5
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
            ephemeral-storage: "1Gi"
          limits:
            ephemeral-storage: "1Gi"
